name = "astrodev/cardanocasino"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'astrodev/cardanocasino'"

[repository]
user = "astrodev"
project = "cardanocasino"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.8.0"
source = "github"
